my updates for gathering failing test coverage

diff --git a/framework/bin/bugsinpy-coverage b/framework/bin/bugsinpy-coverage
--- a/framework/bin/bugsinpy-coverage
+++ b/framework/bin/bugsinpy-coverage
@@ -64,12 +64,22 @@ rm -f "$work_dir/coverage_alltest_bugsinpy.txt"
 
 ###Activate environment
 cd "$work_dir"
-if [ -d "env/Scripts" ]; then
-  source env/Scripts/activate
-else
-  source env/bin/activate
+. /opt/conda/etc/profile.d/conda.sh
+# Cleanup requirements.txt from unwanted spaces
+sed -i -e '/^\s*#.*$/d' -e '/^\s*$/d' "$work_dir/bugsinpy_requirements.txt"
+# dos2unix is required to make sure requirements.txt is always the correct encoding
+dos2unix $work_dir/bugsinpy_requirements.txt &>/dev/null
+# Generate unique hash for the current enviroment
+bug_python_version=$(grep -o "3\..\.." "$work_dir/bugsinpy_bug.info")
+conda_env_name=$(cat <(echo $bug_python_version) "$work_dir/bugsinpy_requirements.txt" | md5sum | cut -d' ' -f 1)
+if ! conda activate $conda_env_name; then
+   echo "Please use 'conda create -n $conda_env_name -y python=$bug_python_version' to create your enviroment first or bugsinpy-testall -p project_name:bug_id"
+   exit
 fi
-pip install coverage
+
+conda install coverage
+
+which python
 
 pytest="0"
 #read file run_test.sh
@@ -104,6 +114,8 @@ if [[ "$pytest" == "1" ]]; then
      echo "$coverage" &>>"$work_dir/coverage_bugsinpy.txt"
   
      coverage_report=$(coverage report -m 2>&1)
+     coverage json
+     mv coverage.json coverage_${index}.json
      echo "$coverage_report"
      printf "\nCoverage Report\n" &>>"$work_dir/coverage_bugsinpy.txt"
      echo "$coverage_report" &>>"$work_dir/coverage_bugsinpy.txt"
@@ -143,6 +155,8 @@ else
      echo "$coverage" &>>"$work_dir/coverage_bugsinpy.txt"
 
      coverage_report=$(coverage report -m 2>&1)
+     coverage json
+     mv coverage.json coverage_${index}.json
      echo "$coverage_report"
      printf "\nCoverage Report\n" &>>"$work_dir/coverage_bugsinpy.txt"
      echo "$coverage_report" &>>"$work_dir/coverage_bugsinpy.txt"
@@ -243,4 +257,4 @@ elif [ "$single_test" != "" ]; then
 fi
 
 ###Deactivate the environment
-deactivate
+conda deactivate
